### PR TITLE
Feature/14178 ess UI add fixed amount to estimated exchange set size

### PR DESCRIPTION
**Pull request by nitu14598**
Hi,

Please review code ,UT and FT changes  for #PBI 14178

Regards!

### CODE REVIEW

**Review by JiviteshT — COMMENTED** [review]
Code looks fine.
Can you make sure target is branch is main and not sprint 6 common? if main then please refresh feature branch from the main.

**Comment by nitu14598** [comment]
yes main is the target branch and also have merged main into this branch

**Review by JiviteshT — APPROVED** [review]

**Review by rvijayavel — APPROVED** [review]
Looks good

**Review by martyn-fewtrell — APPROVED** [review]
Looks good

**Pull request merged**
