### PR TITLE
Feature/13256 ess UI accessibility page update wording

### PR DESCRIPTION
**Pull request by prasad14878**

### CODE REVIEW

**Review by JiviteshT — COMMENTED** [review]
Changes look fine.
Can you make sure feature branch is not supposed to be merged to spring 6 common branch and main instead?

**Review by JiviteshT — APPROVED** [review]

**Review by rvijayavel — APPROVED** [review]
looks good

**Review by rvijayavel — APPROVED** [review]
Change looks fine.

**Review by martyn-fewtrell — APPROVED** [review]
Looks good

**Pull request merged**
