### PR TITLE
Feature/14177 drag file for upload

### PR DESCRIPTION
**Pull request by suraj49470**
added functionality to show error message if  invalid file is dragged and uploaded.

### CODE REVIEW

**Review by JiviteshT — COMMENTED** [review]
Code looks fine.
Can you make sure this branch is supposed to be merged to main and not spring 6 common?

**Review by rvijayavel — APPROVED** [review]
Looks good

**Comment by suraj49470** [comment]
> Code looks fine. Can you make sure this branch is supposed to be merged to main and not spring 6 common?

@JiviteshT it should target main branch. thanks

**Review by JiviteshT — APPROVED** [review]

**Review by martyn-fewtrell — APPROVED** [review]
Looks good

**Pull request merged**
