### PR TITLE
Feature/file parse implementation ess

### PR DESCRIPTION
**Pull request by gaurav15233**
Hi All, Please review and merge changes related to upload CSV file for ESS ui in **ess-ui-main** branch.

### CODE REVIEW

**Review by crdandoukho — COMMENTED** [review]
It looks to me that the behaviour for a 'Valid header only' CSV file is incorrect. I would have expected  the UI to display an error message but it doesn't. Could you please investigate?
I have attached the file
[ValidHeaderOnly.csv](https://github.com/UKHO/file-share-service-ui/files/7774006/ValidHeaderOnly.csv)

**Review by crdandoukho — COMMENTED** [review]
'Drag and drop' of a CSV file only partially works - the filename is displayed but the file content isn't

**Comment by gaurav15233** [comment]
> 'Drag and drop' of a CSV file only partially works - the filename is displayed but the file content isn't

Thanks Chris, for reviewing this. We have not consider drag n drop option in the scope of this PBI. We will work on it in the upcoming sprint.

**Comment by gaurav15233** [comment]
> It looks to me that the behaviour for a 'Valid header only' CSV file is incorrect. I would have expected the UI to display an error message but it doesn't. Could you please investigate? I have attached the file [ValidHeaderOnly.csv](https://github.com/UKHO/file-share-service-ui/files/7774006/ValidHeaderOnly.csv)

Thanks Chris for reviewing this. I tried uploading attach file and received expected validation. Please find below screenshot for 
reference. If you want we can connect on this.

image

**Comment by crdandoukho** [comment]
> It looks to me that the behaviour for a 'Valid header only' CSV file is incorrect. I would have expected the UI to display an error message but it doesn't. Could you please investigate? I have attached the file [ValidHeaderOnly.csv](https://github.com/UKHO/file-share-service-ui/files/7774006/ValidHeaderOnly.csv)

Hi

**Comment by gaurav15233** [comment]
> It looks to me that the behaviour for a 'Valid header only' CSV file is incorrect. I would have expected the UI to display an error message but it doesn't. Could you please investigate? I have attached the file [ValidHeaderOnly.csv](https://github.com/UKHO/file-share-service-ui/files/7774006/ValidHeaderOnly.csv)

Thanks Chris for connect over call. I have fixed both the issues related Valid header and Header&Space csv discussed in call. Can you please review.

**Review by crdandoukho — APPROVED** [review]
Looks good to me. Thanks Gaurav.

**Review by barrie-cooper — APPROVED** [review]
LGTM

**Pull request merged**
