### PR TITLE
Feature/14135 screen adjustments

### PR DESCRIPTION
**Pull request by suraj49470**
added some textual changes and css changes for ess pages

### CODE REVIEW

**Review by JiviteshT — APPROVED** [review]
Looks good.

**Review by rvijayavel — APPROVED** [review]
Looks good

**Review by crdandoukho — CHANGES_REQUESTED** [review]
Suraj, could you please resolve the merge conflicts. 13030 recently went into main, and main then went into the common branch, and now you have merge conflicts. Sorry

**Comment by suraj49470** [comment]
> Suraj, could you please resolve the merge conflicts. 13030 recently went into main, and main then went into the common branch, and now you have merge conflicts. Sorry

@crdandoukho conflicts resolved.

**Review by crdandoukho — APPROVED** [review]
Looks good. Thanks for resolving the conflicts Suraj

**Pull request merged**
