### PR TITLE
10991-fss-ui-re-visit-accessibility-screen Updated text to A AB#12222

### PR DESCRIPTION
**Pull request by Rajesh14881**
Updated Text To A

### CODE REVIEW

**Review by gregzealley — APPROVED** [review]

**Review by bhalcha13813 — APPROVED** [review]
Looks good

**Review by bhalcha13813 — CHANGES_REQUESTED** [review]
Can be merged once resolution issue is resolved observed for high resolution screens.

**Review by martyn-fewtrell — APPROVED** [review]
Looks good

**Comment by pradnya13705** [comment]
> Can be merged once resolution issue is resolved for search and accessibility screen observed for high resolution screens.

Resolution issue is resolved now for search and accessibility screen observed for high resolution screens.

**Review by martyn-fewtrell — APPROVED** [review]
Looks good

**Pull request merged**
