### PR TITLE
12393 fss refactor accessibility tests to single entire page test

### PR DESCRIPTION
**Pull request by kajalkundu**
This pull request is for refactor of the automated accessibility test to check the accessibility on page level not elements level.

### CODE REVIEW

**Review by crdandoukho — COMMENTED** [review]
Hi Kajal, do your changes mean we are no longer checking the search results table?

**Comment by kajalkundu** [comment]
> Hi Kajal, do your changes mean we are no longer checking the search results table?

Yes for automated accessibility we are checking violation for entire page not individual component.

**Review by crdandoukho — CHANGES_REQUESTED** [review]
Kajal, I think we need to check conformance of the search page each time the content is dynamically altered. It appears to me that only the final state of the search page is checked (though it's highly likely I'm misunderstanding how the tests work!).
I think we need the following workflow:
[Load initial page] > [Check a11y] > [Log in] > [Check a11y] > [Populate search criteria] > [Check a11y] > [Check search result] > [Check a11y]

**Review by crdandoukho — APPROVED** [review]
LGTM

**Review by bhalcha13813 — APPROVED** [review]

**Review by gregzealley — APPROVED** [review]

**Review by barrie-cooper — APPROVED** [review]
LGTM

**Pull request merged**
