### PR TITLE
Feature/61736 ess ui update file upload size estimate/main

### PR DESCRIPTION
**Pull request by nitu14598**
Hi,

Please review PBI# **14532 ess ui update file upload size estimate** reference of the same is added under ESS board on PBI#61736. Code changes added and  Unit test , Functional Test is fixed as part of this PBI

Regards!

### CODE REVIEW

**Comment by martyn-fewtrell** [comment]
Hi Nitu - I was looking for Feature/61736 on the FSS Backlog and can't see it so not sure why the work is going on (although i could guess). I may have missed it but could you point me in the correct direction?

**Comment by martyn-fewtrell** [comment]
Sorry just seen comments at the top!

If we are making changes to FSS Project could we add something on the FSS board, please (even if it is just a reference to the other PBI)

**Review by RaviK2233 — APPROVED** [review]

**Review by rvijayavel — APPROVED** [review]
Looks good.

**Review by martyn-fewtrell — APPROVED** [review]
Looks good

**Pull request merged**
