### PR TITLE
Feature/13015 handle unauthenticated user scenarios

### PR DESCRIPTION
**Pull request by suraj49470**
added unauthenticated user scenarios for exchange sets.

### CODE REVIEW

**Review by crdandoukho — CHANGES_REQUESTED** [review]
Code changes look good

Please fix the failing functional tests

**Comment by suraj49470** [comment]
> Code changes look good
> 
> Please fix the failing functional tests

**Review by crdandoukho — APPROVED** [review]
Looks good

**Review by bhalcha13813 — APPROVED** [review]
LGTM

**Pull request merged**
