### PR TITLE
Feature/14127 accessibility testing for exchange sets list view page

### PR DESCRIPTION
**Pull request by pratibh14837**
This PR Contains code changes related to accessibility testing for exchange sets list view page

### CODE REVIEW

**Review by JiviteshT — COMMENTED** [review]
Should it be targeting main branch?

**Comment by pratibh14837** [comment]
Yes..  There is no common code changes so this PR should target to main.

**Comment by JiviteshT** [comment]
> Yes.. There is no common code changes so this PR should target to main.

Thanks for checking.

**Comment by JiviteshT** [comment]
> > Yes.. There is no common code changes so this PR should target to main.
> 
> Thanks for checking.

**Review by crdandoukho — APPROVED** [review]

**Pull request merged**
