### PR TITLE
Feature/71307 fss UI exchange sets remove ability to request aio encs

### PR DESCRIPTION
**Pull request by Satyam15302**
Hi,

 This PR contains PBI#71307 fss UI exchange sets remove ability to request 'AIO' ENCs implementation, unit test and Functional test is fixed as part of this PBI. Kindly review....

https://dev.azure.com/ukhydro/ENC%20Publishing/_sprints/taskboard/ENC%20Publishing%20Team/ENC%20Publishing/Sprint%2011?workitem=71307

Regards!

### CODE REVIEW

**Review by RaviK2233 — APPROVED** [review]
Reviewed FT

**Review by rvijayavel — APPROVED** [review]
Looks good.

**Review by RaviK2233 — APPROVED** [review]
Reviewed FT

**Review by JiviteshT — APPROVED** [review]
Looks fine to me.

**Pull request merged**
